### ISSUE TITLE
Could not pass event StructureGrowEvent to Gastronomicon vBuild 12 (git b84bf75) java.lang.NoClassDefFoundError: net/guizhanss/guizhanlib/slimefun/utils/BlockStorageUtil         at S_[美食家]Gastronomicon-Build 12 (git b84bf75).jar/

### ISSUE THREAD

**Issue by hed516** [SlimefunGuguProject/Gastronomicon#17]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Gastronomicon/issues)，且没有找到相同的问题

### 问题描述

[01:41:16 ERROR]: Could not pass event StructureGrowEvent to Gastronomicon vBuild 12 (git b84bf75)
java.lang.NoClassDefFoundError: net/guizhanss/guizhanlib/slimefun/utils/BlockStorageUtil
        at S_[美食家]Gastronomicon-Build 12 (git b84bf75).jar/io.github.schntgaispock.gastronomicon.core.listeners.TreeGrowthListener.onTreeGrow(TreeGrowthListener.java:21) ~[S_[美食家]Gastronomicon-Build 12 (git b84bf75).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor432.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:84) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:59) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1226) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:844) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:907) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:408) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1804) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.guizhanss.guizhanlib.slimefun.utils.BlockStorageUtil
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 22 more

### 复现步骤

111

### 预期行为

111111111111

### 服务端软件

Spigot

### Minecraft 版本

1。21。1

### Slimefun版本

最新

### 插件版本

最新

**Comment by ybw0014** [comment]
已修复 16a9ce4
